mkdir src
touch App.js
mkdir src/assets
mkdir src/components
mkdir src/components/Home
touch src/components/Home/HomeScreen.js
touch src/components/Home/HomeScreen.test.js
touch src/components/Home/styles.js
mkdir src/components/Home/components
touch src/components/Home/components/index.js
mkdir src/components/PokemonDetails
touch src/components/PokemonDetails/PokemonDetailsScreen.js
touch src/components/PokemonDetails/PokemonDetailsScreen.test.js
touch src/components/PokemonDetails/styles.js
mkdir src/components/PokemonDetails/components
touch src/components/PokemonDetails/components/index.js
mkdir src/screens
mkdir src/screens/Home
touch src/screens/Home/HomeScreen.js
touch src/screens/Home/HomeScreen.test.js
touch src/screens/Home/styles.js
mkdir src/screens/Home/components
touch src/screens/Home/components/index.js
mkdir src/screens/PokemonDetails
touch src/screens/PokemonDetails/PokemonDetailsScreen.js
touch src/screens/PokemonDetails/PokemonDetailsScreen.test.js
touch src/screens/PokemonDetails/styles.js
mkdir src/screens/PokemonDetails/components
touch src/screens/PokemonDetails/components/index.js
mkdir src/services
touch src/services/api.js
mkdir src/store
touch src/store/index.js
mkdir src/store/pokemon
touch src/store/pokemon/pokemonSlice.js
touch src/store/pokemon/pokemonSlice.test.js
mkdir src/utils
touch src/utils/colors.js
touch src/utils/constants.js